import { Footer } from '@/components/Footer';
import { Header } from '@/components/Header';
import { MainContent } from '@/components/MainContent';
import { RollInfo } from '@/components/RollInfo';
import styles from '@/styles/Home.module.css';
import { Inter } from 'next/font/google';
import Head from 'next/head';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
	return (
		<>
			<Head>
				<title>d20 Dice Roller</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<main className={styles.main}>
				<Header />
				<MainContent />
				<Footer />
				<RollInfo />
			</main>
		</>
	);
}
